language: swift
os: osx
osx_image: xcode12.2
xcode_workspace: Demo-SwiftDatabase/Demo-SwiftDatabase.xcworkspace
xcode_scheme: Demo-SwiftDatabase
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone X
podfile: Demo-SwiftDatabase/Podfile
